---
  - name: Grundkonfiguration DC2
    hosts: dc2
    gather_facts: no
    tasks:

      - name: Set Hostname
        ansible.windows.win_hostname:
          name: DC2

      - name: Set Interface Name
        ansible.windows.win_shell: |
          Get-NetAdapter Ethernet0 | Rename-NetAdapter -NewName "VIE_InfraSrv"
      
      - name: Set DNS
        ansible.windows.win_shell: |
          Set-DnsClientServerAddress -InterfaceAlias "VIE_InfraSrv" -ServerAddresses ("10.2.1.1")

      - name: Set Timezone
        ansible.windows.win_shell: |
          Set-TimeZone -Id "W. Europe Standard Time"

      - name: Set Timezone
        ansible.windows.win_shell: |
          Set-NetFirewallRule -Name "FPS-ICMP4-ERQ-In" -Enabled True
          Set-NetFirewallRule -Name "FPS-ICMP4-ERQ-Out" -Enabled True
      
      - name: Enable PS-Remoting
        ansible.windows.win_shell: |
          Enable-PSRemoting -Force
      
      - name: Neustart durchf√ºhren
        win_reboot:
          reboot_timeout: 600
          test_command: hostname
